services:
  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "5001:5001"

  product_service:
    build: ./product_service
    container_name: product_service
    ports:
      - "5002:5002"

  order_service:
    build: ./order_service
    container_name: order_service
    ports:
      - "5004:5004"
    depends_on:
      - user_service
      - product_service

  gateway_dashboard:
    build: ./gateway_dashboard
    container_name: gateway_dashboard
    ports:
      - "8080:8080"
    depends_on:
      - user_service
      - product_service
      - order_service
